[package]
name = "build-workshop"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "build-workshop"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
ctrlc.workspace = true
flate2.workspace = true
tar.workspace = true
workspace-hack.workspace = true

[dev-dependencies]
tempfile.workspace = true

[build-dependencies]
build-ceiling.workspace = true

[lints]
workspace = true
